project:
  title: "jmppeft"
  type: website
  output-dir: docs
  render:
    - "./public-notebooks/**/*.ipynb"

format:
  html:
    theme: default
    page-layout: full
    toc: true
    code-fold: true
    code-summary: "Show code"

website:
  reader-mode: true
