#!/bin/bash
set -e

# Generated using: `python ./scripts/distrelaxer.py generate --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/ --world-size 16 --available-gpu-indices 0 1 2 3 --use-fp64`

screen -dmS relaxer-0 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-0 --world-size 16 --rank 0 --use-fp64 --gpu-index 0
screen -dmS relaxer-1 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-1 --world-size 16 --rank 1 --use-fp64 --gpu-index 1
screen -dmS relaxer-2 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-2 --world-size 16 --rank 2 --use-fp64 --gpu-index 2
screen -dmS relaxer-3 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-3 --world-size 16 --rank 3 --use-fp64 --gpu-index 3
screen -dmS relaxer-4 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-4 --world-size 16 --rank 4 --use-fp64 --gpu-index 0
screen -dmS relaxer-5 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-5 --world-size 16 --rank 5 --use-fp64 --gpu-index 1
screen -dmS relaxer-6 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-6 --world-size 16 --rank 6 --use-fp64 --gpu-index 2
screen -dmS relaxer-7 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-7 --world-size 16 --rank 7 --use-fp64 --gpu-index 3
screen -dmS relaxer-8 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-8 --world-size 16 --rank 8 --use-fp64 --gpu-index 0
screen -dmS relaxer-9 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-9 --world-size 16 --rank 9 --use-fp64 --gpu-index 1
screen -dmS relaxer-10 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-10 --world-size 16 --rank 10 --use-fp64 --gpu-index 2
screen -dmS relaxer-11 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-11 --world-size 16 --rank 11 --use-fp64 --gpu-index 3
screen -dmS relaxer-12 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-12 --world-size 16 --rank 12 --use-fp64 --gpu-index 0
screen -dmS relaxer-13 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-13 --world-size 16 --rank 13 --use-fp64 --gpu-index 1
screen -dmS relaxer-14 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-14 --world-size 16 --rank 14 --use-fp64 --gpu-index 2
screen -dmS relaxer-15 conda run --prefix /net/csefiles/coc-fung-cluster/nima/miniforge3/envs/jmp-peft --live-stream python /net/csefiles/coc-fung-cluster/nima/shared/repositories/jmp-peft/./scripts/distrelaxer.py relax --ckpt-path /net/csefiles/coc-fung-cluster/nima/shared/experiment-data/lltrainer/vye03sc4/checkpoint/last.ckpt --save-dir /net/csefiles/coc-fung-cluster/nima/relaxation-dump-7-7-full/jmp-s2-asefilter-full-frechet-fmax05-v4/rank-15 --world-size 16 --rank 15 --use-fp64 --gpu-index 3
